# version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: nodejs-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./out:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
